### ISSUE TITLE
unrelated... help

### ISSUE THREAD

**Issue by amar3lo** [DenisBY/adjusting#1]
hi DenisBY! 
this is totally unrelatable but i was trying to use your [class/code](https://github.com/lukecyca/pyzabbix/issues/95#issuecomment-351421671) in my zabbix project and two issues came out.
how do i add 'zapi.session.verify=False' to this class?
i try something like: `self.zapi = ZabbixAPI(self.options['https://zabbix.labtest.com.br', 'zapi.session.verify=False'])`

but i don't know if is right because i keep getting `TypeError: __init__() missing 1 required positional argument: 'options'`

i know this is completely unrelatable (again... beside python, i'm also learning english ) but your code seems to me very objective and teaching.. thanks in advance

**Comment by DenisBY** [comment]
Hi,

It was in 2017. Probably something changed since then in the library. Anyway it's better to ask here https://github.com/lukecyca/pyzabbix/issues
